#!/usr/bin/env ruby

require 'open3'

url1 = ARGV.shift
url2 = ARGV.shift

cmd = "docker run -i rranshous/imgcompare"
#cmd = "docker run -i ubuntu:14.04 cat"
puts "running cmd: #{cmd}"
Open3.popen3(cmd) do |i, o, e, t|
  puts "writing input"
  i.sync = true
  i.write "#{url1}\n#{url2}\n"
  i.flush
  puts "waiting on read"
  r = o.read
  puts "R: #{r}"
end

