#!/usr/bin/env ruby

require 'open3'

loop do

  url1 = ARGV.shift
  url2 = ARGV.shift

  break if url1.nil? || url2.nil?

  cmd = "docker run -i rranshous/imgcompare_distributed"
  puts "running cmd: #{cmd}"
  Open3.popen3(cmd) do |i, o, e, t|
    puts "writing input"
    i.sync = true
    i.write "#{url1}\n#{url2}\n"
    i.flush
    puts "waiting on read"
    r = o.gets
    puts "R: #{r}"
  end

end
