#!/usr/bin/env ruby

require 'tempfile'
require 'base64'
require 'httparty'
require 'phashion'
require_relative 'download_and_compare'

# takes two urls via stdin
# protocol is:
# URL1\nURL2\n
# than responds with
# VALUE\n

STDOUT.sync = true
STDERR.sync = true

def parse_stdin
  STDERR.puts "reading first from stdin"
  url1 = STDIN.gets
  url1 = url1.strip if url1
  STDERR.puts "first from stdin: #{url1}"
  STDERR.puts "reading second from stdin"
  url2 = STDIN.gets
  url2 = url2.strip if url2
  STDERR.puts "second from stdin: #{url2}"
  [url1, url2]
end

def validate! *inputs
  inputs.each do |input|
    if input.nil? || input.strip == ''
      exit 0
    end
  end
end

def cycle
  STDERR.puts "cycling"
  image_url1, image_url2 = parse_stdin

  validate! image_url1, image_url2

  comparer = Comparer.new
  downloader = Downloader.new
  diff = :ERROR
  STDERR.puts "downloading"
  downloader.download(image_url1, image_url2) do |path1, path2|
    STDERR.puts "comparing"
    diff = comparer.compare path1, path2
  end

  STDOUT.puts diff
  STDOUT.flush
end

loop do
  cycle
end
